
build_task:
  container:
    image: leiniercs/acrb:30
    cpu: 1
    memory: 1G
    #kvm: true
    greedy: true

  name: ACRB-30
  timeout_in: 4h

  sync_script: bash sync.sh
  build_script: bash build.sh
  publish_script: bash publish.sh
