build_task:
  persistent_worker:
    labels:
      name: AX61-1
    isolation:
      container:
        image: leiniercs/acrb:30
        cpu: 1
        memory: 1G
        volumes:
          - /home/cirrus/roms:/home/ci/roms
#          - /home/cirrus/ccache:/home/ci/ccache
#          - /home/cirrus/.config:/home/ci/.config

  name: Build Android Custom ROM
#  timeout_in: 4h
  sync_script: bash sync.sh
#  build_script: bash build.sh
#  publish_script: bash publish.sh
