container:
  image: cirrusci/android-sdk:30-ndk
  cpu: 8
  memory: 32G

env:
  BUILD_HOSTNAME: "cirrus-ci.org"
  GIT_NAME: "Leinier Cruz Salfran"
  GIT_EMAIL: "leiniercs@gmail.com"
  DEVICE: "garden"
  ROM: "pixelexperience"
  USE_CCACHE: 1
  CCACHE_DIR: "$CIRRUS_WORKING_DIR/ccache/$DEVICE/$ROM"

build_task:
  name: Build PixelExperience AOSP
  rom_cache:
    folder: "$CIRRUS_WORKING_DIR/$DEVICE/$ROM"
  install_prerequisites_script: bash $CIRRUS_WORKING_DIR/install_prerequisites.sh
  sync_script: bash $CIRRUS_WORKING_DIR/sync.sh
  build_script: bash $CIRRUS_WORKING_DIR/build.sh
  publish_script: bash $CIRRUS_WORKING_DIR/publish.sh
