build_task:
  container:
    image: leiniercs/acrb:30
    cpu: 8
    memory: 32G
#    kvm: true
#    greedy: true

  name: ACRB-30

  env:
    KBUILD_BUILD_HOST: "cirrus-ci.org"
    KBUILD_BUILD_USER: "ci"
    BUILD_HOSTNAME: "cirrus-ci.org"
    BUILD_USERNAME: "ci"
    GIT_NAME: "Leinier Cruz Salfran"
    GIT_EMAIL: "leiniercs@gmail.com"
    DEVICE: "dandelion"
    ROM_REPO: "LineageOS/android"
    ROM_BRANCH: "lineage-20.0"
    ROM_BUILD: "lineage_dandelion-user"
    LOCAL_MANIFEST_REPO: "leiniercs/android_local_manifest"
    LOCAL_MANIFEST_BRANCH: "lineageos"

#  custom_script: bash custom.sh
  sync_script: bash sync.sh
  build_script: bash build.sh
  publish_script: bash publish.sh
