container:
  image: leiniercs/acrb:30
  cpu: 8
  memory: 24G

env:
  BUILD_HOSTNAME: "cirrus-ci.org"
  GIT_NAME: "Leinier Cruz Salfran"
  GIT_EMAIL: "leiniercs@gmail.com"
  DEVICE: "garden"
  ROM: "PixelExperience"
  FLAVOR: "twelve-plus"

build_task:
  name: Build PixelExperience ROM
  rom_cache:
    folder: "~/$DEVICE/$ROM/$FLAVOR"
  sync_script: bash -eo pipefail sync.sh
  build_script: bash -eo pipefail build.sh
  publish_script: bash -eo pipefail publish.sh
