export KBUILD_BUILD_HOST=cloud.google.com
export KBUILD_BUILD_USER=ci
export BUILD_HOSTNAME=cloud.google.com
export BUILD_USERNAME=ci
export GIT_NAME=Leinier
export GIT_EMAIL=leiniercs@gmail.com
export DEVICE=dandelion
export ROM_REPO=LineageOS/android
export ROM_BRANCH=lineage-19.1
export ROM_BUILD=lineage_dandelion-user
export LOCAL_MANIFEST_REPO=leiniercs/android_local_manifest
export LOCAL_MANIFEST_BRANCH=lineageos
export NCPU=$(nproc --all)
export HOME=/home/ci
