steps:
  - label: "Build AOSP"
    plugins:
      - docker#v3.13.0:
          image: "leiniercs/acrb:30"
          cpus: "32"
          memory: "64gb"
          storage-opt: "size=200G"
          user: "ci"
          propagate-environment: true
          workdir: "/home/ci"
    timeout_in_minutes: 240
    env:
      KBUILD_BUILD_HOST=ci.buildkite.com
      KBUILD_BUILD_USER=ci
      BUILD_HOSTNAME=ci.buildkite.com
      BUILD_USERNAME=ci
      GIT_NAME=Leinier
      GIT_EMAIL=leiniercs@gmail.com
      DEVICE=dandelion
      ROM_REPO=LineageOS/android
      ROM_BRANCH=lineage-19.1
      ROM_BUILD=lineage_dandelion-user
      LOCAL_MANIFEST_REPO=leiniercs/android_local_manifest
      LOCAL_MANIFEST_BRANCH=lineageos
    command: "/usr/bin/build.sh"
