version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/android-sdk:30-ndk
    environment:
      BUILD_HOSTNAME: "circleci.com"
      BUILD_USERNAME: "ci"
      DEBIAN_FRONTEND: "noninteractive"
      TZ: "UTC"
      GIT_NAME: "Leinier Cruz Salfran"
      GIT_EMAIL: "leiniercs@gmail.com"
      DEVICE: "garden"
      ROM: "PixelExperience"
      FLAVOR: "twelve-plus"
      ROM_DIR: "~/roms/$DEVICE/$ROM/$FLAVOR"
      USE_CCACHE: 1
      CCACHE_DIR: "~/ccache/$DEVICE/$ROM/$FLAVOR"
    steps:
      - checkout
      - run: bash install_prerequisites.sh
      - run: bash sync.sh
      - run: bash build.sh
      - run: bash publish.sh
