name: ACRB
on: push
jobs:
  acrb:
    name: ACRB
    runs-on: buildjet-32vcpu-ubuntu-2204
    container:
      image: leiniercs/acrb:30
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v3
    - name: Clean Up
      run: |
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean
    - name: Build
      run: |
        df -h
