name: Build Android Custom ROM

on: push

jobs:
  acrb_job:
    runs-on: ubuntu-22.04
    container:
      image: docker://leiniercs/acrb:30

    steps:
      - name: Verifying things
        run: |
          ls -la /usr/bin/nsjail
          echo "====="
#      - name: Checkout
#        uses: actions/checkout@v2.1.0
#        run: git clone https://github.com/leiniercs/android_local_manifest .

#      - name: Synchronization
#        run: bash sync.sh

#      - name: Building
#        run: bash build.sh

#      - name: Publishing
#        run: bash publish.sh

