name: ACRB
on: push
jobs:
  acrb:
    name: ACRB
    runs-on: buildjet-32vcpu-ubuntu-2204
    container:
      image: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          df -h
          pwd
          ls
