name: Build Android Custom ROM

on: push

jobs:
  acrb_job:
    runs-on: ubuntu-22.04
    container:
      image: docker://leiniercs/acrb:30

    steps:
      - name: Checkout
        run: git clone https://github.com/leiniercs/android_local_manifest .

      - name: Synchronization
        run: bash sync.sh

      - name: Building
        run: bash build.sh

      - name: Publishing
        run: bash publish.sh

