name: Build Android Custom ROM

on: push

jobs:
  build_aosp_job:
    container:
      image: docker://leiniercs/acrb:30

  steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0

    - name: Synchronization
      run: bash sync.sh

    - name: Building
      run: bash build.sh

    - name: Publishing
      run: bash publish.sh

