name: ACRB
on: push
jobs:
  test:
    runs-on: buildjet-2vcpu-ubuntu-2204
    container:
      image: leiniercs/acrb:30
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          nproc
          free -h
          df -h
