name: ACRB
on: push
jobs:
  acrb:
    name: ACRB
    runs-on: buildjet-32vcpu-ubuntu-2204
    container:
      image: ubuntu
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v3
    - name: Clean Up
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean
        sudo apt update
    - name: Install packages
      run: |
        sudo apt full-upgrade -y
    - name: Build
      run: |
        df -h
