name: ACRB
on: push
jobs:
  acrb:
    name: ACRB
    runs-on: buildjet-32vcpu-ubuntu-2204
    container:
      image: ubuntu
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v3
    - name: Clean Up
      run: |
        rm -rf /usr/share/dotnet /etc/mysql /etc/php
        apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        apt -y autoremove --purge
        apt -y autoclean
        apt clean
        apt update
    - name: Install packages
      run: |
        apt -y full-upgrade
    - name: Build
      run: |
        df -h
