name: ACRB
on: push
jobs:
  acrb:
    name: ACRB
    runs-on: buildjet-32vcpu-ubuntu-2204
    container:
      image: ubuntu
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          df -h
          pwd
          ls
