name: Specs

on: push

jobs:
  specs:
    name: Specs
    runs-on: buildjet-32vcpu-ubuntu-2204
    timeout-minutes: 5

    steps:
      - name: Show
        run: |
          nproc
          free -h
          df -h

